version: '3'

services:
  mongodbserv:
    image: mongo:5.0.3
    container_name: mongodbserv
    hostname: mongodbserv
    ports:
      - "37017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - formy
networks:
  formy:
    driver: bridge