spring:
  data:
    mongodb:
      host: localhost
      port: 37017
      database: forevermoneyapi_db
      username: admin
      password: admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
